server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/oauth2/authorization/**, /user-service/login/oauth2/code/**
            - Method= GET, POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/user/**
            - Method= GET, POST, PATCH, DELETE
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthenticationFilter

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event-service/**
            - Method= GET, POST, PATCH, DELETE
          filters:
            - RewritePath=/event-service/(?<segment>.*), /$\{segment}
            - AuthenticationFilter
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/report-service/**
            - Method= GET, POST, PATCH, DELETE
          filters:
            - RewritePath=/report-service/(?<segment>.*), /$\{segment}
            - AuthenticationFilter

jwt:
  secret: as2189d1o2mocqem31x1c3o34m3c4owlkf13orm134oirmt134oitm341i1io34tm43i1om12o4fim059gk0259g4m
