server:
  port: 0

spring:
  application:
    name: event-service
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/event-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: @YOUR_USERNAME@
    password: @YOUR_PASSWORD@
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

openapi:
  key: @YOUR_OPENAPI_KEY@